[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datalog-syntax = { path = "../datalog-syntax" }
datalog_rule_macro = { path = "../datalog_rule_macro" }
petgraph = "0.6.4"
itertools = "0.14.0"
